POST http://localhost:3003/api/users/
Content-Type: application/json

{
  "username": "root",
  "name": "root",
  "password": "password"
}

###

http://localhost:3003/api/users/

###
http://localhost:3001/api/users/delete