http://localhost:3001/api/notes/

###

http://localhost:3001/api/notes/1

###

DELETE http://localhost:3001/api/notes/1

###

POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content" : "prueba",
    "important" : true
}

